rearrange psql start

diff --git a/customize b/customize
--- a/customize
+++ b/customize
@@ -78,22 +78,26 @@ echo "* Install postgresql"
 apt-get update
 apt-get install -y postgresql postgresql-contrib
 
+echo "* Fix postgresql for lx-branch"
+sed -i -e "s|PIDFile=|#PIDFile=|" /lib/systemd/system/postgresql@.service
+systemctl daemon-reload
+pg_createcluster ${PG_VERSION} main --start || true
+
 echo "* Setup postgresql"
-sed -i \
-    -e "s/#listen_addresses = 'localhost'/listen_addresses = 'localhost'/" \
-    /etc/postgresql/${PG_VERSION}/main/postgresql.conf
-echo "local all kivitendo password" >> /etc/postgresql/${PG_VERSION}/main/pg_hba.conf
-echo "host all kivitendo 127.0.0.1 255.255.255.255 password" >> /etc/postgresql/${PG_VERSION}/main/pg_hba.conf
+if [[ -d "/etc/postgresql/${PG_VERSION}/main" ]]; then
+  sed -i \
+      -e "s/#listen_addresses = 'localhost'/listen_addresses = 'localhost'/" \
+      /etc/postgresql/${PG_VERSION}/main/postgresql.conf
+  echo "local all kivitendo password" >> /etc/postgresql/${PG_VERSION}/main/pg_hba.conf
+  echo "host all kivitendo 127.0.0.1 255.255.255.255 password" >> /etc/postgresql/${PG_VERSION}/main/pg_hba.conf
+else
+  echo "* ERROR: /etc/postgresql/${PG_VERSION}/main missing"
+fi
 
 echo "* Copy kivitendo postgresql setup"
 mv /usr/local/var/tmp/psql_kivi_user.sql /usr/local/src/kivitendo-erp/config/psql_kivi_user.sql
 mv /usr/local/var/tmp/psql_kivi_superuser.sql /usr/local/src/kivitendo-erp/config/psql_kivi_superuser.sql
 mv /usr/local/var/tmp/psql_kivi_template1.sql /usr/local/src/kivitendo-erp/config/psql_kivi_template1.sql
-
-echo "* Fix postgresql for lx-branch"
-sed -i -e "s|PIDFile=|#PIDFile=|" /lib/systemd/system/postgresql@.service
-systemctl daemon-reload
-pg_createcluster ${PG_VERSION} main --start || true
 
 echo "* Setup postgresql backup"
 mkdir -p /var/lib/postgresql/backups
